### PR TITLE
fix: allow coercion of nested properties [3.x]

### LINKED ISSUE #1723: Mongo Extended operators in updateAll not working
# Description/Steps to reproduce

Merge request #1702 broke functionality of  extended operators in `updateAll` operation on the models.

The new line added in `dao.js` [here](https://github.com/strongloop/loopback-datasource-juggler/blob/df4366eb3114a7e16673ce1b4d29044ab33bf094/lib/dao.js#L2306) stores in `ctx.data` the **object** representation of the created instance from the above line, so this is the final value passed in the connector update method which handles the data update.

This has the effect that any passed extended operators such as in **MongoDB** `$set` is stripped from the update data because `.toObject` does not take into account any extended operators that might have been given in the update data, which is referenced here: https://loopback.io/doc/en/lb3/MongoDB-connector.html

So basically you cannot use extended operators in `updateAll` function.

To find out the result just issue an update on a model that has enabled the use of `allowExtendedOperators` such as  `Model.updateAll({}, { $set: { prop: 'sth'} })`

# Expected result

It should pass the given extended operators in the update object and let the MongoDB Connector handle them appropriately.

# Additional information

linux x64 10.15.3
├── loopback@3.25.1
├── loopback-connector-mongodb@4.1.0

### PR DESCRIPTION
**Pull request by b-admike**
### Description

Fixes #1723. Make sure we coerce nested property values for DAO methods like `updateAll`.

### Checklist

- [x] New tests added or existing tests modified to cover all changes
- [x] Code conforms with the [style
  guide](http://loopback.io/doc/en/contrib/style-guide.html)

### CODE REVIEW

**Comment by b-admike** [comment]
@strongloop/sq-lb-apex @mitsos1os PTAL

**Comment by b-admike** [comment]
@slnode test please

File: lib/model-utils.js [hunk 1]
```diff
@@ -551,3 +568,15 @@ ModelUtils._coerce = function(where, options) {
...
+/**
+* A utility function which checks for nested property definitions
+*
+* @param {*} propType Property type metadata
+*
+*/
+function isNestedModel(propType) {
+  if (!propType) return false;
+  if (Array.isArray(propType)) return isNestedModel(propType[0]);
+  return propType.definition && propType.definition.properties;
```
Comment (mitsos1os) [inline lib/model-utils.js]: Here an actual boolean could be returned to keep function signature consistent. ex:
`return !!(propType.definition && propType.definition.properties;` or 
`return propType.hasOwnProperty('definition') && propType.definition.hasOwnProperty('properties');`

File: lib/model-utils.js [hunk 2]
```diff
@@ -391,6 +397,17 @@ ModelUtils._coerce = function(where, options) {
...
+    if (isNestedModel(DataType)) {
+      if (Array.isArray(DataType)) {
+        if (value === null || value === undefined) continue;
+        for (const it of value) {
+          self._coerce(it, options, DataType[0].definition);
+        }
+      } else {
+        self._coerce(value, options, DataType.definition);
+      }
+    }
```
Comment (mitsos1os) [inline lib/model-utils.js]: I might be missing something here, but by taking a quick look, if **nested** model is found, couldn't it just `continue` on to next iteration instead of following the rest of the logic?

Comment (b-admike) [reply lib/model-utils.js]: If the nested model is not an array, then we are recursively sending its `definition` to use with the `_coerce` function here.

Comment (mitsos1os) [reply lib/model-utils.js]: Yes I understand that. I was talking about using a `continue`  before closing the **NestedModel** is between line 409 and 410

Comment (b-admike) [reply lib/model-utils.js]: I see what you mean now thank you for clarifying. If the model is nested, then it either checks for array or not but either way it calls `self._coerce()`. Would it be better if I re-wrote this as follows (without the `else` block)?
```js
    if (isNestedModel(DataType)) {
      if (Array.isArray(DataType)) {
        if (value === null || value === undefined) continue;
        for (const it of value) {
          self._coerce(it, options, DataType[0].definition);
        }
      } 
        self._coerce(value, options, DataType.definition);
    }
```

**Comment by b-admike** [comment]
Thanks for your feedback @mitsos1os. LGTY now?

**Comment by mitsos1os** [comment]
@b-admike LGTM! Thanks for reviewing the feedback!

**Comment by b-admike** [comment]
@slnode test please
